export const list = [
  {
    id: '1',
    nodes: [
      {
        id: "node_1",
        position: {
          x: 0,
          y: 150,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Introduction to Digital Logic Design",
        },
        width: 311,
        height: 57,
      },
      {
        id: "node_1_children",
        type: "group",
        position: {
          x: -350,
          y: -200,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_1_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Understanding binary numbers",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 269,
        height: 59,
      },
      {
        id: "node_1_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Combinational logic",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 183,
        height: 59,
      },
      {
        id: "node_1_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Sequential logic",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 154,
        height: 59,
      },
      {
        id: "node_1_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Finite State Machines",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 196,
        height: 59,
      },
      {
        id: "node_1_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Logic synthesis",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 151,
        height: 59,
      },
      {
        id: "node_2",
        position: {
          x: 0,
          y: 300,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Basic Verilog Concepts",
        },
        width: 215,
        height: 57,
      },
      {
        id: "node_2_children",
        type: "group",
        position: {
          x: 400,
          y: 550,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_2_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Verilog syntax and semantics",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 255,
        height: 59,
        selected: true,
        dragging: false,
      },
      {
        id: "node_2_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Data types and operators",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 226,
        height: 59,
      },
      {
        id: "node_2_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Modules and port definitions",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 251,
        height: 59,
      },
      {
        id: "node_2_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Behavioral modeling",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 187,
        height: 59,
      },
      {
        id: "node_2_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Structural modeling",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 183,
        height: 59,
      },
      {
        id: "node_3",
        position: {
          x: 0,
          y: 450,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Simulation",
        },
        width: 150,
        height: 57,
      },
      {
        id: "node_3_children",
        type: "group",
        position: {
          x: -600,
          y: 350,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_3_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Writing test benches",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 190,
        height: 59,
      },
      {
        id: "node_3_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Using simulators like ModelSim or Icarus Verilog",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 397,
        height: 59,
      },
      {
        id: "node_3_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Debugging Verilog code",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 216,
        height: 59,
      },
      {
        id: "node_3_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Waveform viewing and analysis",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 270,
        height: 59,
      },
      {
        id: "node_3_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Test coverage",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_4",
        position: {
          x: 6,
          y: 606,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Synthesis",
        },
        width: 150,
        height: 57,
        selected: false,
        positionAbsolute: {
          x: 6,
          y: 606,
        },
        dragging: false,
      },
      {
        id: "node_4_children",
        type: "group",
        position: {
          x: 800,
          y: 1100,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
        selected: false,
        dragging: false,
      },
      {
        id: "node_4_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Understanding synthesis constraints",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 311,
        height: 59,
      },
      {
        id: "node_4_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Synthesis tools like Synopsys Design Compiler",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 386,
        height: 59,
      },
      {
        id: "node_4_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Analyzing synthesis reports",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 243,
        height: 59,
      },
      {
        id: "node_4_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Gate-level netlists",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 170,
        height: 59,
      },
      {
        id: "node_4_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Optimizing designs for speed or area",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 313,
        height: 59,
      },
      {
        id: "node_5",
        position: {
          x: -40,
          y: 752,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "RTL Coding Best Practices",
        },
        width: 243,
        height: 57,
        selected: false,
        positionAbsolute: {
          x: -40,
          y: 752,
        },
        dragging: false,
      },
      {
        id: "node_5_children",
        type: "group",
        position: {
          x: -350,
          y: 900,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_5_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Writing synthesizable code",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 238,
        height: 59,
      },
      {
        id: "node_5_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Avoiding common pitfalls",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 223,
        height: 59,
      },
      {
        id: "node_5_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Coding for performance",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 216,
        height: 59,
      },
      {
        id: "node_5_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Design reusability",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 168,
        height: 59,
      },
      {
        id: "node_5_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Code reviews",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_6",
        position: {
          x: 0,
          y: 900,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Advanced Verilog Features",
        },
        width: 245,
        height: 57,
      },
      {
        id: "node_6_children",
        type: "group",
        position: {
          x: 400,
          y: 1650,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_6_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Generate constructs",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 189,
        height: 59,
      },
      {
        id: "node_6_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Interfaces",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_6_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Parameterized modules",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 213,
        height: 59,
      },
      {
        id: "node_6_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Assertion-based verification",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 247,
        height: 59,
      },
      {
        id: "node_6_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "SystemVerilog fundamentals",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 250,
        height: 59,
      },
      {
        id: "node_7",
        position: {
          x: 0,
          y: 1050,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Verification Concepts",
        },
        width: 203,
        height: 57,
      },
      {
        id: "node_7_children",
        type: "group",
        position: {
          x: -600,
          y: 1450,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_7_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Functional verification",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 200,
        height: 59,
      },
      {
        id: "node_7_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Coverage-driven verification",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 249,
        height: 59,
      },
      {
        id: "node_7_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Using assertions",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 160,
        height: 59,
      },
      {
        id: "node_7_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Verification methodologies",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 236,
        height: 59,
      },
      {
        id: "node_7_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Universal Verification Methodology (UVM)",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 352,
        height: 59,
      },
      {
        id: "node_8",
        position: {
          x: 0,
          y: 1200,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Hardware Prototyping and Testing",
        },
        width: 304,
        height: 57,
      },
      {
        id: "node_8_children",
        type: "group",
        position: {
          x: 800,
          y: 2200,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_8_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Field Programmable Gate Arrays (FPGAs)",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 347,
        height: 59,
      },
      {
        id: "node_8_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Translating RTL to FPGA",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 218,
        height: 59,
      },
      {
        id: "node_8_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "On-chip debugging",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 182,
        height: 59,
      },
      {
        id: "node_8_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Performance testing",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 188,
        height: 59,
      },
      {
        id: "node_8_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Prototyping boards",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 179,
        height: 59,
      },
      {
        id: "node_9",
        position: {
          x: 0,
          y: 1350,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Industry Tools and Methodologies",
        },
        width: 301,
        height: 57,
      },
      {
        id: "node_9_children",
        type: "group",
        position: {
          x: -350,
          y: 2000,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_9_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Version control systems",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 215,
        height: 59,
      },
      {
        id: "node_9_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Continuous integration in hardware",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 299,
        height: 59,
      },
      {
        id: "node_9_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Scripting with Perl/Python for automation",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 345,
        height: 59,
      },
      {
        id: "node_9_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "EDA tools comparison",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 201,
        height: 59,
      },
      {
        id: "node_9_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "IP-based design",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 157,
        height: 59,
      },
    ],
    edges: [
      {
        id: "node_1_to_child_1",
        source: "node_1",
        target: "node_1_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_2",
        source: "node_1",
        target: "node_1_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_3",
        source: "node_1",
        target: "node_1_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_4",
        source: "node_1",
        target: "node_1_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_5",
        source: "node_1",
        target: "node_1_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_1",
        source: "node_2",
        target: "node_2_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_2",
        source: "node_2",
        target: "node_2_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_3",
        source: "node_2",
        target: "node_2_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_4",
        source: "node_2",
        target: "node_2_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_5",
        source: "node_2",
        target: "node_2_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_1_to_node_2",
        source: "node_1",
        target: "node_2",
        type: "mainPathEdge",
      },
      {
        id: "node_3_to_child_1",
        source: "node_3",
        target: "node_3_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_2",
        source: "node_3",
        target: "node_3_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_3",
        source: "node_3",
        target: "node_3_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_4",
        source: "node_3",
        target: "node_3_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_5",
        source: "node_3",
        target: "node_3_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_2_to_node_3",
        source: "node_2",
        target: "node_3",
        type: "mainPathEdge",
      },
      {
        id: "node_4_to_child_1",
        source: "node_4",
        target: "node_4_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_2",
        source: "node_4",
        target: "node_4_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_3",
        source: "node_4",
        target: "node_4_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_4",
        source: "node_4",
        target: "node_4_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_5",
        source: "node_4",
        target: "node_4_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_3_to_node_4",
        source: "node_3",
        target: "node_4",
        type: "mainPathEdge",
      },
      {
        id: "node_5_to_child_1",
        source: "node_5",
        target: "node_5_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_2",
        source: "node_5",
        target: "node_5_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_3",
        source: "node_5",
        target: "node_5_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_4",
        source: "node_5",
        target: "node_5_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_5",
        source: "node_5",
        target: "node_5_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_4_to_node_5",
        source: "node_4",
        target: "node_5",
        type: "mainPathEdge",
      },
      {
        id: "node_6_to_child_1",
        source: "node_6",
        target: "node_6_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_2",
        source: "node_6",
        target: "node_6_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_3",
        source: "node_6",
        target: "node_6_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_4",
        source: "node_6",
        target: "node_6_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_5",
        source: "node_6",
        target: "node_6_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_5_to_node_6",
        source: "node_5",
        target: "node_6",
        type: "mainPathEdge",
      },
      {
        id: "node_7_to_child_1",
        source: "node_7",
        target: "node_7_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_2",
        source: "node_7",
        target: "node_7_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_3",
        source: "node_7",
        target: "node_7_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_4",
        source: "node_7",
        target: "node_7_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_5",
        source: "node_7",
        target: "node_7_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_6_to_node_7",
        source: "node_6",
        target: "node_7",
        type: "mainPathEdge",
      },
      {
        id: "node_8_to_child_1",
        source: "node_8",
        target: "node_8_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_2",
        source: "node_8",
        target: "node_8_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_3",
        source: "node_8",
        target: "node_8_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_4",
        source: "node_8",
        target: "node_8_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_5",
        source: "node_8",
        target: "node_8_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_7_to_node_8",
        source: "node_7",
        target: "node_8",
        type: "mainPathEdge",
      },
      {
        id: "node_9_to_child_1",
        source: "node_9",
        target: "node_9_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_2",
        source: "node_9",
        target: "node_9_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_3",
        source: "node_9",
        target: "node_9_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_4",
        source: "node_9",
        target: "node_9_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_5",
        source: "node_9",
        target: "node_9_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_8_to_node_9",
        source: "node_8",
        target: "node_9",
        type: "mainPathEdge",
      },
    ],
  },
  {
    id: '2',
    nodes: [
      {
        id: "node_1",
        position: {
          x: 0,
          y: 150,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Pre-Calculus Review",
        },
        width: 196,
        height: 57,
      },
      {
        id: "node_1_children",
        type: "group",
        position: {
          x: -350,
          y: -200,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_1_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Functions, Domains, and Ranges",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 282,
        height: 59,
      },
      {
        id: "node_1_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Trigonometry Basics",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 189,
        height: 59,
      },
      {
        id: "node_1_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Graphs of Basic Functions",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 232,
        height: 59,
      },
      {
        id: "node_1_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Complex Numbers",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 174,
        height: 59,
      },
      {
        id: "node_1_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Sequences and Series",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 202,
        height: 59,
      },
      {
        id: "node_2",
        position: {
          x: 0,
          y: 300,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Limits and Continuity",
        },
        width: 201,
        height: 57,
      },
      {
        id: "node_2_children",
        type: "group",
        position: {
          x: 400,
          y: 550,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_2_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Understanding Limits",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 195,
        height: 59,
      },
      {
        id: "node_2_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Evaluating Limits",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 161,
        height: 59,
      },
      {
        id: "node_2_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Limits Involving Infinity",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 205,
        height: 59,
      },
      {
        id: "node_2_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Continuity of Functions",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 210,
        height: 59,
      },
      {
        id: "node_2_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Intermediate Value Theorem",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 248,
        height: 59,
      },
      {
        id: "node_3",
        position: {
          x: 0,
          y: 450,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Differentiation",
        },
        width: 150,
        height: 57,
      },
      {
        id: "node_3_children",
        type: "group",
        position: {
          x: -600,
          y: 350,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_3_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Derivatives and Rates of Change",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 280,
        height: 59,
      },
      {
        id: "node_3_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Basic Differentiation Rules",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 232,
        height: 59,
      },
      {
        id: "node_3_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Product and Quotient Rules",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 243,
        height: 59,
      },
      {
        id: "node_3_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Chain Rule",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_3_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Implicit Differentiation",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 200,
        height: 59,
      },
      {
        id: "node_4",
        position: {
          x: 0,
          y: 600,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Applications of Derivatives",
        },
        width: 244,
        height: 57,
      },
      {
        id: "node_4_children",
        type: "group",
        position: {
          x: 800,
          y: 1100,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_4_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Maxima and Minima",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 184,
        height: 59,
      },
      {
        id: "node_4_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Mean Value Theorem",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 194,
        height: 59,
      },
      {
        id: "node_4_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Graphing with Derivatives",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 228,
        height: 59,
      },
      {
        id: "node_4_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Optimization Problems",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 206,
        height: 59,
      },
      {
        id: "node_4_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Related Rates",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_5",
        position: {
          x: 0,
          y: 750,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Integration",
        },
        width: 150,
        height: 57,
      },
      {
        id: "node_5_children",
        type: "group",
        position: {
          x: -350,
          y: 900,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_5_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Antiderivatives",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_5_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Definite Integrals",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 162,
        height: 59,
      },
      {
        id: "node_5_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Fundamental Theorem of Calculus",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 294,
        height: 59,
      },
      {
        id: "node_5_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Integration Techniques",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 207,
        height: 59,
      },
      {
        id: "node_5_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Numerical Integration",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 197,
        height: 59,
      },
      {
        id: "node_6",
        position: {
          x: 0,
          y: 900,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Applications of Integration",
        },
        width: 243,
        height: 57,
      },
      {
        id: "node_6_children",
        type: "group",
        position: {
          x: 400,
          y: 1650,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_6_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Area Under a Curve",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 182,
        height: 59,
      },
      {
        id: "node_6_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Volumes of Solids of Revolution",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 272,
        height: 59,
      },
      {
        id: "node_6_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Arc Length",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_6_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Work and Energy",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 163,
        height: 59,
      },
      {
        id: "node_6_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Fluid Pressure and Force",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 221,
        height: 59,
      },
      {
        id: "node_7",
        position: {
          x: 0,
          y: 1050,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Differential Equations",
        },
        width: 204,
        height: 57,
      },
      {
        id: "node_7_children",
        type: "group",
        position: {
          x: -600,
          y: 1450,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_7_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Separable Equations",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 189,
        height: 59,
      },
      {
        id: "node_7_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "First-Order Linear Equations",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 248,
        height: 59,
      },
      {
        id: "node_7_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Direction Fields",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 151,
        height: 59,
      },
      {
        id: "node_7_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Euler's Method",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_7_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Second-Order Differential Equations",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 309,
        height: 59,
      },
      {
        id: "node_8",
        position: {
          x: 0,
          y: 1200,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Sequences and Series",
        },
        width: 208,
        height: 57,
      },
      {
        id: "node_8_children",
        type: "group",
        position: {
          x: 800,
          y: 2200,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_8_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Convergent and Divergent Series",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 284,
        height: 59,
      },
      {
        id: "node_8_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Tests for Convergence",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 204,
        height: 59,
      },
      {
        id: "node_8_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Power Series",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_8_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Taylor and Maclaurin Series",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 242,
        height: 59,
      },
      {
        id: "node_8_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Fourier Series",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 150,
        height: 59,
      },
      {
        id: "node_9",
        position: {
          x: 0,
          y: 1350,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Multivariable Calculus",
        },
        width: 207,
        height: 57,
      },
      {
        id: "node_9_children",
        type: "group",
        position: {
          x: -350,
          y: 2000,
        },
        style: {
          width: 150,
          background: "none",
          height: 500,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 500,
      },
      {
        id: "node_9_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Partial Derivatives",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 169,
        height: 59,
      },
      {
        id: "node_9_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Multiple Integrals",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 164,
        height: 59,
      },
      {
        id: "node_9_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Vector Calculus",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 153,
        height: 59,
      },
      {
        id: "node_9_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Green's Theorem",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 165,
        height: 59,
      },
      {
        id: "node_9_child_5",
        type: "childNode",
        position: {
          x: 0,
          y: 320,
        },
        data: {
          label: "Divergence and Curl",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 188,
        height: 59,
      },
    ],
    edges: [
      {
        id: "node_1_to_child_1",
        source: "node_1",
        target: "node_1_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_2",
        source: "node_1",
        target: "node_1_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_3",
        source: "node_1",
        target: "node_1_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_4",
        source: "node_1",
        target: "node_1_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_5",
        source: "node_1",
        target: "node_1_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_1",
        source: "node_2",
        target: "node_2_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_2",
        source: "node_2",
        target: "node_2_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_3",
        source: "node_2",
        target: "node_2_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_4",
        source: "node_2",
        target: "node_2_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_5",
        source: "node_2",
        target: "node_2_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_1_to_node_2",
        source: "node_1",
        target: "node_2",
        type: "mainPathEdge",
      },
      {
        id: "node_3_to_child_1",
        source: "node_3",
        target: "node_3_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_2",
        source: "node_3",
        target: "node_3_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_3",
        source: "node_3",
        target: "node_3_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_4",
        source: "node_3",
        target: "node_3_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_5",
        source: "node_3",
        target: "node_3_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_2_to_node_3",
        source: "node_2",
        target: "node_3",
        type: "mainPathEdge",
      },
      {
        id: "node_4_to_child_1",
        source: "node_4",
        target: "node_4_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_2",
        source: "node_4",
        target: "node_4_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_3",
        source: "node_4",
        target: "node_4_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_4",
        source: "node_4",
        target: "node_4_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_5",
        source: "node_4",
        target: "node_4_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_3_to_node_4",
        source: "node_3",
        target: "node_4",
        type: "mainPathEdge",
      },
      {
        id: "node_5_to_child_1",
        source: "node_5",
        target: "node_5_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_2",
        source: "node_5",
        target: "node_5_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_3",
        source: "node_5",
        target: "node_5_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_4",
        source: "node_5",
        target: "node_5_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_5",
        source: "node_5",
        target: "node_5_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_4_to_node_5",
        source: "node_4",
        target: "node_5",
        type: "mainPathEdge",
      },
      {
        id: "node_6_to_child_1",
        source: "node_6",
        target: "node_6_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_2",
        source: "node_6",
        target: "node_6_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_3",
        source: "node_6",
        target: "node_6_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_4",
        source: "node_6",
        target: "node_6_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_5",
        source: "node_6",
        target: "node_6_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_5_to_node_6",
        source: "node_5",
        target: "node_6",
        type: "mainPathEdge",
      },
      {
        id: "node_7_to_child_1",
        source: "node_7",
        target: "node_7_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_2",
        source: "node_7",
        target: "node_7_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_3",
        source: "node_7",
        target: "node_7_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_4",
        source: "node_7",
        target: "node_7_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_5",
        source: "node_7",
        target: "node_7_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_6_to_node_7",
        source: "node_6",
        target: "node_7",
        type: "mainPathEdge",
      },
      {
        id: "node_8_to_child_1",
        source: "node_8",
        target: "node_8_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_2",
        source: "node_8",
        target: "node_8_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_3",
        source: "node_8",
        target: "node_8_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_4",
        source: "node_8",
        target: "node_8_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_5",
        source: "node_8",
        target: "node_8_child_5",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_7_to_node_8",
        source: "node_7",
        target: "node_8",
        type: "mainPathEdge",
      },
      {
        id: "node_9_to_child_1",
        source: "node_9",
        target: "node_9_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_2",
        source: "node_9",
        target: "node_9_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_3",
        source: "node_9",
        target: "node_9_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_4",
        source: "node_9",
        target: "node_9_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_5",
        source: "node_9",
        target: "node_9_child_5",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_8_to_node_9",
        source: "node_8",
        target: "node_9",
        type: "mainPathEdge",
      },
    ],
  },
  {
    id: '3',
    nodes: [
      {
        id: "node_1",
        position: {
          x: 0,
          y: 150,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Understanding Variables and Expressions",
        },
        width: 362,
        height: 57,
      },
      {
        id: "node_1_children",
        type: "group",
        position: {
          x: -350,
          y: -200,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_1_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Introduction to variables",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 217,
        height: 59,
      },
      {
        id: "node_1_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Working with expressions",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 227,
        height: 59,
      },
      {
        id: "node_1_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Combining like terms",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 193,
        height: 59,
      },
      {
        id: "node_1_child_4",
        type: "childNode",
        position: {
          x: -0.8041067761806744,
          y: 240,
        },
        data: {
          label: "The distributive property",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_1_children",
        width: 221,
        height: 59,
        selected: true,
        positionAbsolute: {
          x: -350.8041067761807,
          y: 40,
        },
        dragging: false,
      },
      {
        id: "node_2",
        position: {
          x: 0,
          y: 300,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Solving Equations",
        },
        width: 174,
        height: 57,
      },
      {
        id: "node_2_children",
        type: "group",
        position: {
          x: 400,
          y: 450,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_2_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "One-step equations",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 185,
        height: 59,
      },
      {
        id: "node_2_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Two-step equations",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 184,
        height: 59,
      },
      {
        id: "node_2_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Equations with variables on both sides",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 324,
        height: 59,
      },
      {
        id: "node_2_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Word problems involving equations",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_2_children",
        width: 300,
        height: 59,
      },
      {
        id: "node_3",
        position: {
          x: 0,
          y: 450,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Solving Inequalities",
        },
        width: 187,
        height: 57,
      },
      {
        id: "node_3_children",
        type: "group",
        position: {
          x: -600,
          y: 250,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_3_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "One-step inequalities",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 196,
        height: 59,
      },
      {
        id: "node_3_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Multi-step inequalities",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 202,
        height: 59,
      },
      {
        id: "node_3_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Graphing inequalities on a number line",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 324,
        height: 59,
      },
      {
        id: "node_3_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Compound inequalities",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_3_children",
        width: 208,
        height: 59,
      },
      {
        id: "node_4",
        position: {
          x: 0,
          y: 600,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Factoring",
        },
        width: 150,
        height: 57,
      },
      {
        id: "node_4_children",
        type: "group",
        position: {
          x: 800,
          y: 900,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_4_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Factors and multiples",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 196,
        height: 59,
      },
      {
        id: "node_4_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Factoring out the greatest common factor",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 350,
        height: 59,
      },
      {
        id: "node_4_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Factoring trinomials",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 183,
        height: 59,
      },
      {
        id: "node_4_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Factoring by grouping",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_4_children",
        width: 200,
        height: 59,
      },
      {
        id: "node_5",
        position: {
          x: 0,
          y: 750,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Functions",
        },
        width: 150,
        height: 57,
      },
      {
        id: "node_5_children",
        type: "group",
        position: {
          x: -350,
          y: 700,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_5_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Understanding functions and their notation",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 359,
        height: 59,
      },
      {
        id: "node_5_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Evaluating functions",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 187,
        height: 59,
      },
      {
        id: "node_5_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Domain and range",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 172,
        height: 59,
      },
      {
        id: "node_5_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Operations with functions",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_5_children",
        width: 229,
        height: 59,
      },
      {
        id: "node_6",
        position: {
          x: 0,
          y: 900,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Linear Equations and Graphs",
        },
        width: 260,
        height: 57,
      },
      {
        id: "node_6_children",
        type: "group",
        position: {
          x: 400,
          y: 1350,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_6_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Slope-intercept form",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 192,
        height: 59,
      },
      {
        id: "node_6_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Point-slope form",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 160,
        height: 59,
      },
      {
        id: "node_6_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Graphing linear equations",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 228,
        height: 59,
      },
      {
        id: "node_6_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Writing equations of lines",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_6_children",
        width: 225,
        height: 59,
      },
      {
        id: "node_7",
        position: {
          x: 0,
          y: 1050,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Systems of Equations",
        },
        width: 204,
        height: 57,
      },
      {
        id: "node_7_children",
        type: "group",
        position: {
          x: -600,
          y: 1150,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_7_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Solving by graphing",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 184,
        height: 59,
      },
      {
        id: "node_7_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Solving using substitution",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 229,
        height: 59,
      },
      {
        id: "node_7_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Solving using elimination",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 221,
        height: 59,
      },
      {
        id: "node_7_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Applications of systems of equations",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_7_children",
        width: 313,
        height: 59,
      },
      {
        id: "node_8",
        position: {
          x: 0,
          y: 1200,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Polynomials",
        },
        width: 150,
        height: 57,
      },
      {
        id: "node_8_children",
        type: "group",
        position: {
          x: 800,
          y: 1800,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_8_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Adding and subtracting polynomials",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 306,
        height: 59,
      },
      {
        id: "node_8_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Multiplying polynomials",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 211,
        height: 59,
      },
      {
        id: "node_8_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Polynomial division",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 178,
        height: 59,
      },
      {
        id: "node_8_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "The Remainder Theorem",
        },
        sourcePosition: "left",
        targetPosition: "left",
        parent: "extent",
        parentNode: "node_8_children",
        width: 221,
        height: 59,
      },
      {
        id: "node_9",
        position: {
          x: 0,
          y: 1350,
        },
        type: "mainNode",
        sourcePosition: "bottom",
        targetPosition: "top",
        data: {
          label: "Quadratic Equations",
        },
        width: 194,
        height: 57,
      },
      {
        id: "node_9_children",
        type: "group",
        position: {
          x: -350,
          y: 1600,
        },
        style: {
          width: 150,
          background: "none",
          height: 400,
          border: "none",
        },
        data: {
          label: "",
        },
        width: 150,
        height: 400,
      },
      {
        id: "node_9_child_1",
        type: "childNode",
        position: {
          x: 0,
          y: 0,
        },
        data: {
          label: "Solving quadratics by factoring",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 269,
        height: 59,
      },
      {
        id: "node_9_child_2",
        type: "childNode",
        position: {
          x: 0,
          y: 80,
        },
        data: {
          label: "Using the quadratic formula",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 244,
        height: 59,
      },
      {
        id: "node_9_child_3",
        type: "childNode",
        position: {
          x: 0,
          y: 160,
        },
        data: {
          label: "Graphing quadratic functions",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 255,
        height: 59,
      },
      {
        id: "node_9_child_4",
        type: "childNode",
        position: {
          x: 0,
          y: 240,
        },
        data: {
          label: "Applications of quadratic equations",
        },
        sourcePosition: "right",
        targetPosition: "right",
        parent: "extent",
        parentNode: "node_9_children",
        width: 302,
        height: 59,
      },
    ],
    edges: [
      {
        id: "node_1_to_child_1",
        source: "node_1",
        target: "node_1_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_2",
        source: "node_1",
        target: "node_1_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_3",
        source: "node_1",
        target: "node_1_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_1_to_child_4",
        source: "node_1",
        target: "node_1_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_1",
        source: "node_2",
        target: "node_2_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_2",
        source: "node_2",
        target: "node_2_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_3",
        source: "node_2",
        target: "node_2_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_2_to_child_4",
        source: "node_2",
        target: "node_2_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_1_to_node_2",
        source: "node_1",
        target: "node_2",
        type: "mainPathEdge",
      },
      {
        id: "node_3_to_child_1",
        source: "node_3",
        target: "node_3_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_2",
        source: "node_3",
        target: "node_3_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_3",
        source: "node_3",
        target: "node_3_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_3_to_child_4",
        source: "node_3",
        target: "node_3_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_2_to_node_3",
        source: "node_2",
        target: "node_3",
        type: "mainPathEdge",
      },
      {
        id: "node_4_to_child_1",
        source: "node_4",
        target: "node_4_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_2",
        source: "node_4",
        target: "node_4_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_3",
        source: "node_4",
        target: "node_4_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_4_to_child_4",
        source: "node_4",
        target: "node_4_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_3_to_node_4",
        source: "node_3",
        target: "node_4",
        type: "mainPathEdge",
      },
      {
        id: "node_5_to_child_1",
        source: "node_5",
        target: "node_5_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_2",
        source: "node_5",
        target: "node_5_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_3",
        source: "node_5",
        target: "node_5_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_5_to_child_4",
        source: "node_5",
        target: "node_5_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_4_to_node_5",
        source: "node_4",
        target: "node_5",
        type: "mainPathEdge",
      },
      {
        id: "node_6_to_child_1",
        source: "node_6",
        target: "node_6_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_2",
        source: "node_6",
        target: "node_6_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_3",
        source: "node_6",
        target: "node_6_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_6_to_child_4",
        source: "node_6",
        target: "node_6_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_5_to_node_6",
        source: "node_5",
        target: "node_6",
        type: "mainPathEdge",
      },
      {
        id: "node_7_to_child_1",
        source: "node_7",
        target: "node_7_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_2",
        source: "node_7",
        target: "node_7_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_3",
        source: "node_7",
        target: "node_7_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_7_to_child_4",
        source: "node_7",
        target: "node_7_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_6_to_node_7",
        source: "node_6",
        target: "node_7",
        type: "mainPathEdge",
      },
      {
        id: "node_8_to_child_1",
        source: "node_8",
        target: "node_8_child_1",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_2",
        source: "node_8",
        target: "node_8_child_2",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_3",
        source: "node_8",
        target: "node_8_child_3",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "node_8_to_child_4",
        source: "node_8",
        target: "node_8_child_4",
        sourceHandle: "right",
        targetHandle: "left",
        type: "childPathEdge",
      },
      {
        id: "edge_node_7_to_node_8",
        source: "node_7",
        target: "node_8",
        type: "mainPathEdge",
      },
      {
        id: "node_9_to_child_1",
        source: "node_9",
        target: "node_9_child_1",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_2",
        source: "node_9",
        target: "node_9_child_2",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_3",
        source: "node_9",
        target: "node_9_child_3",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "node_9_to_child_4",
        source: "node_9",
        target: "node_9_child_4",
        sourceHandle: "left",
        targetHandle: "right",
        type: "childPathEdge",
      },
      {
        id: "edge_node_8_to_node_9",
        source: "node_8",
        target: "node_9",
        type: "mainPathEdge",
      },
    ],
  },
];
